<?php

return [
    'Dashboard' => 'Operations and financial visibility from one control center',
    'Reports Center' => 'Track cross-module metrics and activity from one command view',
    'Request Communications' => 'Track inbox notifications and delivery status across approval flows',
    'Request Reports' => 'Analyze request volume, approval speed, and response timing health',
    'Vendor Profile' => 'View vendor profile, invoices, payments, and statement timeline',
    'Vendor Reports' => 'Track request-expense-vendor traceability and unlinked spend gaps',
    'Communications' => 'Configure organization notification channels and fallback order',
    'Approval Timing Controls' => 'Configure approval response timing, reminder, and escalation policy',
    'Company Setup' => 'Create your company and baseline department',
    'Expense Controls' => 'Set which roles can post, edit, and void expenses per organization policy',
    'Asset Controls' => 'Set which roles can manage asset registration, custody, maintenance, and disposal',
    'Vendor Controls' => 'Set which roles can manage vendor profiles, invoices, payments, exports, and communications',
    'Tenant / Organization Management' => 'Tenant control center for lifecycle, plans, billing defaults, seat governance, and entitlements',
    'Tenant Details' => 'Billing ledger, reconciliation queue, plan history, usage quotas, and tenant audit timeline',
    'Platform Users' => 'Assign and manage global platform roles for tenant operations and billing governance',
    'Assets' => 'Track assets from registration to assignment, maintenance, and disposal',
    'Asset Reports' => 'Analyze asset distribution, maintenance spend, and disposal trends',
    'Organization Hierarchy' => 'Manage departments, reporting lines, role ownership, and approval chains',
    'Request Configuration' => 'Configure request types and spend categories for your organization',
    'Departments' => 'Create departments and maintain department head assignments',
    'Approval Workflows' => 'Configure policy chains and approval routing for requests',
    'Team' => 'Manage staff accounts, role ownership, and reporting hierarchy',
];
